### PR TITLE
Fixed glitch bars on console

### PR DESCRIPTION
**Pull request by TechdudeGames**

### CODE REVIEW

**Comment by TechdudeGames** [comment]
Let me know if this modification is alright. I tested on console and it worked so I think all should be good.

**Comment by fgsfdsfgs** [comment]
This got me thinking about possible different approaches to solve this problem. Stay tuned.

**Comment by TechdudeGames** [comment]
Sounds good to me!

**Comment by fgsfdsfgs** [comment]
I got a PS2 now, so I can properly look into this. Unfortunately I don't have component cables, so can't check progressive resolutions.

**Comment by fgsfdsfgs** [comment]
I will also be absent for the following 5 days, so I'll merge this in the meantime.

**Comment by TechdudeGames** [comment]
Oh cool! If you need some testing done I have a PS2 with component cables so I can see if I can't do some testing.

**Pull request merged**
